     1|# TYPE  DATABASE  USER            ADDRESS     METHOD
     2|local   all       postgres                    trust
     3|local   all       all                         trust
     4|hostssl all       REDACTED_USER   0.0.0.0/0   cert clientcert=verify-full
     5|hostssl all       REDACTED_USER   ::/0        cert clientcert=verify-full
     6|hostssl all       REDACTED_USER    0.0.0.0/0   cert clientcert=verify-full
     7|hostssl all       REDACTED_USER    ::/0        cert clientcert=verify-full
     8|