# TYPE  DATABASE  USER            ADDRESS     METHOD
local   all       postgres                    trust
local   all       all                         trust
hostssl all       rp_readwrite    0.0.0.0/0   cert clientcert=verify-full
hostssl all       rp_readwrite    ::/0        cert clientcert=verify-full
hostssl all       rp_readonly     0.0.0.0/0   cert clientcert=verify-full
hostssl all       rp_readonly     ::/0        cert clientcert=verify-full
