     1|#!/bin/bash
     2|set -e
     3|
     4|# pg_hba.conf는 command line arg로 직접 지정됨 (-c hba_file=...)
     5|# 그래서 여기서는 유저 생성만 수행
     6|
     7|psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
     8|  CREATE USER REDACTED_USER WITH PASSWORD '${DEV_READWRITE_PWD}';
     9|  GRANT ALL PRIVILEGES ON DATABASE postgres TO REDACTED_USER;
    10|  ALTER USER REDACTED_USER CREATEDB;
    11|
    12|  CREATE USER REDACTED_USER WITH PASSWORD '${ALL_READONLY_PWD}';
    13|  GRANT CONNECT ON DATABASE postgres TO REDACTED_USER;
    14|
    15|  GRANT ALL ON SCHEMA public TO REDACTED_USER;
    16|  GRANT USAGE ON SCHEMA public TO REDACTED_USER;
    17|
    18|  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO REDACTED_USER;
    19|  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO REDACTED_USER;
    20|  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO REDACTED_USER;
    21|  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO REDACTED_USER;
    22|EOSQL
    23|